version: '3.8'

services:
  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/task_manager
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - task_manager_network
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"  # Run migrations before starting the app

  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: task_manager_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task_manager
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task_manager_network

# Volumes to persist data
volumes:
  postgres-data:

# Networks to allow communication between services
networks:
  task_manager_network:
    driver: bridge
